// Generated by gencpp from file final_pkg/vector_m.msg
// DO NOT EDIT!


#ifndef FINAL_PKG_MESSAGE_VECTOR_M_H
#define FINAL_PKG_MESSAGE_VECTOR_M_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace final_pkg
{
template <class ContainerAllocator>
struct vector_m_
{
  typedef vector_m_<ContainerAllocator> Type;

  vector_m_()
    : avaiable_points()  {
    }
  vector_m_(const ContainerAllocator& _alloc)
    : avaiable_points(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Point_<ContainerAllocator> >::other >  _avaiable_points_type;
  _avaiable_points_type avaiable_points;




  typedef boost::shared_ptr< ::final_pkg::vector_m_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::final_pkg::vector_m_<ContainerAllocator> const> ConstPtr;

}; // struct vector_m_

typedef ::final_pkg::vector_m_<std::allocator<void> > vector_m;

typedef boost::shared_ptr< ::final_pkg::vector_m > vector_mPtr;
typedef boost::shared_ptr< ::final_pkg::vector_m const> vector_mConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::final_pkg::vector_m_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::final_pkg::vector_m_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace final_pkg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'final_pkg': ['/home/parallels/wsfinal/src/final_pkg/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::final_pkg::vector_m_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::final_pkg::vector_m_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::final_pkg::vector_m_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::final_pkg::vector_m_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::final_pkg::vector_m_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::final_pkg::vector_m_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::final_pkg::vector_m_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1e4e4c7924162920dede83839967ccfc";
  }

  static const char* value(const ::final_pkg::vector_m_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1e4e4c7924162920ULL;
  static const uint64_t static_value2 = 0xdede83839967ccfcULL;
};

template<class ContainerAllocator>
struct DataType< ::final_pkg::vector_m_<ContainerAllocator> >
{
  static const char* value()
  {
    return "final_pkg/vector_m";
  }

  static const char* value(const ::final_pkg::vector_m_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::final_pkg::vector_m_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Point[] avaiable_points\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::final_pkg::vector_m_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::final_pkg::vector_m_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.avaiable_points);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct vector_m_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::final_pkg::vector_m_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::final_pkg::vector_m_<ContainerAllocator>& v)
  {
    s << indent << "avaiable_points[]" << std::endl;
    for (size_t i = 0; i < v.avaiable_points.size(); ++i)
    {
      s << indent << "  avaiable_points[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.avaiable_points[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // FINAL_PKG_MESSAGE_VECTOR_M_H
